formatting

diff --git a/rootfs/templates/wrapper b/rootfs/templates/wrapper
--- a/rootfs/templates/wrapper
+++ b/rootfs/templates/wrapper
@@ -118,12 +118,12 @@ function use() {
 			done
 		fi
 
-    if [ -z "${local_home}" ]; then
-      echo "ERROR: can't identify user home directory, you may specify path via LOCAL_HOME variable"
-      exit 1
-    else
-      echo "Detected Windows Subsystem for Linux, mounting $local_home instead of $HOME"
-    fi
+		if [ -z "${local_home}" ]; then
+			echo "ERROR: can't identify user home directory, you may specify path via LOCAL_HOME variable"
+			exit 1
+		else
+			echo "Detected Windows Subsystem for Linux, mounting $local_home instead of $HOME"
+		fi
 
 	else
 		local_home=${HOME}
